<!DOCTYPE html>
<html>
<head>
<meta charset="ISO-8859-1">
<title>Tournament Participant Inputs</title>
</head>
<body>
<div style="width:250px"><h3>Tournament Winner Inputs</h3>

<form action="TourneyBracketOutputsServlet" method="post" id="form1">
   <button type="submit" form="form1" value="player1">player1</button> <br>
   <button type="submit" form="form1" value="player2">player2</button> <br>
</form>


</div>
</body>
</html>
